# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269122e3919c9064e907c8133d8bdf687e80e1ca8908afdb1e598a3bd3bb73d081151bcec07164ac0bacbd8e7cc545e78a803c2fab6b64be762d09018694adc2

test:
  secret_key_base: b2ba64cee0bca13bf28de2b48a4d7a8bb96a5dfc23329d263bc0287ec251e96448b159ee84fcab73eb145713745a552a61678cf4fadefa9a29c471c8934501af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
